// web/site/src/lib/components/ui/Table.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    zebra?: boolean;
    header?: Snippet;
    footer?: Snippet;
    children?: Snippet;
  }

  let { zebra = false, header, footer, children }: Props = $props();
</script>

<div class="w-full overflow-x-auto">
  <table class="w-full border-collapse">
    {#if header}
      <thead class="border-b border-gray-200 bg-gray-50">
        {@render header()}
      </thead>
    {/if}
    <tbody class={zebra ? "divide-y divide-gray-200" : ""}>
      {@render children?.()}
    </tbody>
    {#if footer}
      <tfoot class="border-t border-gray-200 bg-gray-50">
        {@render footer()}
      </tfoot>
    {/if}
  </table>
</div>

<style>
  tbody.divide-y :global(> tr:nth-child(even)) {
    background-color: #f9fafb;
  }

  tbody :global(> tr:hover) {
    background-color: #f3f4f6;
  }
</style>

// web/src/components/ui/Table.vue
<template>
  <div class="w-full overflow-x-auto">
    <table class="w-full border-collapse">
      <thead v-if="$slots.header" class="border-b border-gray-200 bg-gray-50">
        <slot name="header" />
      </thead>
      <tbody :class="zebra ? 'divide-y divide-gray-200' : ''">
        <slot />
      </tbody>
      <tfoot v-if="$slots.footer" class="border-t border-gray-200 bg-gray-50">
        <slot name="footer" />
      </tfoot>
    </table>
  </div>
</template>

<script setup lang="ts">
interface Props {
  zebra?: boolean;
}

withDefaults(defineProps<Props>(), {
  zebra: false
});
</script>

<style scoped>
tbody.divide-y > tr:nth-child(even) {
  background-color: #f9fafb;
}

tbody > tr:hover {
  background-color: #f3f4f6;
}
</style>
