// web/private/src/lib/components/layout/Sidebar.svelte
<script lang="ts">
  /**
   * Dark 64px icon rail (WS2 primaryMenu / twing-m):
   * logo at top, section icons in the middle, user and logout at bottom.
   */
  import { onMount } from "svelte";
  import { page } from "$app/state";
  import { t } from "@/i18n/index.svelte";
  import { logout } from "@/utils/auth";
  import SvgIcon from "@/components/SvgIcon.svelte";
  import { useCurrentUser } from "@/composables/useCurrentUser.svelte";

  const currentUser = useCurrentUser();

  onMount(() => {
    currentUser.loadUserData();
  });

  function isActive(path: string): boolean {
    return page.url.pathname.startsWith(path);
  }

  const navItems = $derived([
    { path: "/dashboard", icon: "dashboard", label: t("navigation.dashboard"), active: isActive("/dashboard") },
    { path: "/submissions", icon: "submissions", label: t("navigation.submissions"), active: isActive("/submissions") },
    { path: "/templates", icon: "templates", label: t("navigation.templates"), active: isActive("/templates") },
    {
      path: "/settings",
      icon: "settings",
      label: t("navigation.settings"),
      active: isActive("/settings") && !isActive("/admin/settings")
    }
  ]);

  const adminNavItems = $derived([
    {
      path: "/admin/organizations",
      icon: "organizations",
      label: t("navigation.organizations"),
      active: isActive("/admin/organizations")
    },
    {
      path: "/admin/settings",
      icon: "settings",
      label: `${t("navigation.administrator")}: ${t("navigation.settings")}`,
      active: isActive("/admin/settings")
    }
  ]);

  const userInitial = $derived(
    currentUser.userData?.first_name
      ? currentUser.userData.first_name[0].toUpperCase()
      : currentUser.userData?.email
        ? currentUser.userData.email[0].toUpperCase()
        : "U"
  );

  const userTitle = $derived.by(() => {
    const name = `${currentUser.userData?.first_name || ""} ${currentUser.userData?.last_name || ""}`.trim();
    const email = currentUser.userData?.email || "";
    return [name, email].filter(Boolean).join(" — ") || t("navigation.user");
  });

  async function handleLogout(): Promise<void> {
    currentUser.clearUser();
    await logout();
  }
</script>

<aside class="app-sidebar">
  <a href="/dashboard" class="sb-brand" title="goSign">
    <span class="sb-logo">
      <SvgIcon name="logo" class="sb-logo-icon" />
    </span>
  </a>

  <nav class="sb-nav">
    {#each navItems as item (item.path)}
      <a href={item.path} class="sb-item" class:active={item.active} title={item.label} aria-label={item.label}>
        <SvgIcon name={item.icon} class="sb-icon" />
      </a>
    {/each}

    {#if currentUser.isAdmin}
      <div class="sb-divider" role="separator" title={t("navigation.administrator")}></div>
      {#each adminNavItems as item (item.path)}
        <a href={item.path} class="sb-item" class:active={item.active} title={item.label} aria-label={item.label}>
          <SvgIcon name={item.icon} class="sb-icon" />
        </a>
      {/each}
    {/if}
  </nav>

  <div class="sb-footer">
    <a href="/settings/general" class="sb-avatar" title={userTitle} aria-label={userTitle}>
      {userInitial}
    </a>
    <button
      type="button"
      class="sb-item sb-item--logout"
      onclick={handleLogout}
      title={t("navigation.exit")}
      aria-label={t("navigation.exit")}
    >
      <SvgIcon name="exit" class="sb-icon" />
    </button>
  </div>
</aside>

<style>
  .sb-brand {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--space-12) 0 var(--space-8);
    flex-shrink: 0;
  }
  .sb-logo {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: var(--size-control-36);
    height: var(--size-control-36);
    border-radius: var(--radius-10);
    background: linear-gradient(135deg, var(--base-hlt-invert), var(--base-hlt-b-invert));
    color: var(--base-txt-alt-light);
  }
  .sb-logo :global(.sb-logo-icon) {
    width: 22px;
    height: 22px;
  }

  .sb-nav {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--space-4);
    padding: var(--space-8) 0;
    overflow-y: auto;
    overflow-x: hidden;
    scrollbar-width: none;
  }

  .sb-divider {
    width: 28px;
    height: 1px;
    margin: var(--space-4) 0;
    background: var(--color-graphite-alpha-d-200);
    flex-shrink: 0;
  }

  .sb-item {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 42px;
    height: 42px;
    border: none;
    background: transparent;
    border-radius: var(--radius-10);
    cursor: pointer;
    transition: var(--transition-colors);
    flex-shrink: 0;
  }
  .sb-item :global(.sb-icon) {
    width: 21px;
    height: 21px;
    flex-shrink: 0;
    color: var(--sidebar-ico-base);
    transition: var(--transition-colors);
  }
  .sb-item:hover {
    background: var(--sidebar-cont-hover);
  }
  .sb-item:hover :global(.sb-icon) {
    color: var(--sidebar-ico-hover);
  }
  .sb-item.active {
    background: var(--sidebar-cont-active);
  }
  .sb-item.active :global(.sb-icon) {
    color: var(--sidebar-ico-active);
  }
  .sb-item:focus-visible {
    outline: none;
    box-shadow: var(--shadow-focus);
  }

  .sb-footer {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--space-8);
    padding: var(--space-8) 0 var(--space-12);
    border-top: 1px solid var(--color-graphite-alpha-d-100);
    flex-shrink: 0;
  }
  .sb-avatar {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 28px;
    height: 28px;
    border-radius: var(--radius-full);
    background: var(--sidebar-cont-active);
    color: var(--sidebar-ico-active);
    font-size: var(--font-size-11);
    font-weight: var(--font-weight-bold);
    text-decoration: none;
    transition: var(--transition-colors);
  }
  .sb-avatar:hover {
    background: var(--sidebar-cont-hover);
    color: var(--sidebar-ico-active);
  }
  .sb-item--logout:hover {
    background: var(--sidebar-cont-hover);
  }
  .sb-item--logout:hover :global(.sb-icon) {
    color: var(--base-txt-alert-minor);
  }
</style>

// web/src/layouts/Sidebar.vue
<template>
  <div class="relative flex h-screen overflow-hidden bg-[var(--color-base-100)]">
    <!-- Sidebar Navigation -->
    <aside
      class="flex h-screen flex-col border-e border-[#e7e2df] bg-white transition-all duration-150"
      :class="isCollapsed ? 'w-16' : 'w-48'"
    >
      <!-- Logo -->
      <div class="flex h-14 items-center border-b border-gray-100 px-3">
        <div class="flex items-center overflow-hidden">
          <SvgIcon name="logo" stroke="currentColor" class="h-6 w-6 flex-shrink-0" />
          <span
            v-show="!isCollapsed"
            class="ml-2.5 text-base font-bold whitespace-nowrap text-gray-800 transition-opacity duration-150"
            :class="isCollapsed ? 'opacity-0' : 'opacity-100'"
          >
            goSign
          </span>
        </div>
      </div>

      <!-- Navigation Menu -->
      <nav class="flex-1 overflow-hidden px-2 py-3">
        <ul class="space-y-0.5">
          <li>
            <RouterLink
              to="/dashboard"
              class="group relative flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100 hover:text-gray-900"
              :class="[{ 'bg-gray-100 text-gray-900': isActive('/dashboard') }, isCollapsed ? 'justify-center' : '']"
              :title="isCollapsed ? $t('navigation.dashboard') : ''"
            >
              <SvgIcon name="dashboard" class="h-4 w-4 flex-shrink-0" />
              <span v-show="!isCollapsed" class="text-[13px] whitespace-nowrap">{{ $t("navigation.dashboard") }}</span>
              <span
                v-if="isCollapsed"
                class="invisible absolute left-full ml-2 rounded-md bg-gray-900 px-2 py-1 text-xs text-white opacity-0 transition-all group-hover:visible group-hover:opacity-100"
              >
                {{ $t("navigation.dashboard") }}
              </span>
            </RouterLink>
          </li>

          <li>
            <RouterLink
              to="/submissions"
              class="group relative flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100 hover:text-gray-900"
              :class="[{ 'bg-gray-100 text-gray-900': isActive('/submissions') }, isCollapsed ? 'justify-center' : '']"
              :title="isCollapsed ? $t('navigation.submissions') : ''"
            >
              <SvgIcon name="submissions" class="h-4 w-4 flex-shrink-0" />
              <span v-show="!isCollapsed" class="text-[13px] whitespace-nowrap">{{
                $t("navigation.submissions")
              }}</span>
              <span
                v-if="isCollapsed"
                class="invisible absolute left-full ml-2 rounded-md bg-gray-900 px-2 py-1 text-xs text-white opacity-0 transition-all group-hover:visible group-hover:opacity-100"
              >
                {{ $t("navigation.submissions") }}
              </span>
            </RouterLink>
          </li>

          <li>
            <RouterLink
              to="/templates"
              class="group relative flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100 hover:text-gray-900"
              :class="[{ 'bg-gray-100 text-gray-900': isActive('/templates') }, isCollapsed ? 'justify-center' : '']"
              :title="isCollapsed ? $t('navigation.templates') : ''"
            >
              <SvgIcon name="templates" class="h-4 w-4 flex-shrink-0" />
              <span v-show="!isCollapsed" class="text-[13px] whitespace-nowrap">{{ $t("navigation.templates") }}</span>
              <span
                v-if="isCollapsed"
                class="invisible absolute left-full ml-2 rounded-md bg-gray-900 px-2 py-1 text-xs text-white opacity-0 transition-all group-hover:visible group-hover:opacity-100"
              >
                {{ $t("navigation.templates") }}
              </span>
            </RouterLink>
          </li>

          <li>
            <RouterLink
              to="/settings"
              class="group relative flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100 hover:text-gray-900"
              :class="[
                { 'bg-gray-100 text-gray-900': isActive('/settings') && !isActive('/admin/settings') },
                isCollapsed ? 'justify-center' : ''
              ]"
              :title="isCollapsed ? $t('navigation.settings') : ''"
            >
              <SvgIcon name="settings" class="h-4 w-4 flex-shrink-0" />
              <span v-show="!isCollapsed" class="text-[13px] whitespace-nowrap">{{ $t("navigation.settings") }}</span>
              <span
                v-if="isCollapsed"
                class="invisible absolute left-full ml-2 rounded-md bg-gray-900 px-2 py-1 text-xs text-white opacity-0 transition-all group-hover:visible group-hover:opacity-100"
              >
                {{ $t("navigation.settings") }}
              </span>
            </RouterLink>
          </li>

          <!-- Administrator Section (only for admins) -->
          <li v-show="isAdmin" class="pt-3">
            <div
              v-show="!isCollapsed"
              class="mb-1.5 px-2.5 text-[11px] font-semibold tracking-wider text-gray-400 uppercase"
            >
              {{ $t("navigation.administrator") }}
            </div>
            <div v-if="isCollapsed" class="mb-1.5 border-t border-gray-200"></div>
          </li>
          <li v-show="isAdmin">
            <RouterLink
              to="/admin/organizations"
              class="group relative flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100 hover:text-gray-900"
              :class="[
                { 'bg-gray-100 text-gray-900': isActive('/admin/organizations') },
                isCollapsed ? 'justify-center' : ''
              ]"
              :title="isCollapsed ? $t('navigation.organizations') : ''"
            >
              <SvgIcon name="organizations" class="h-4 w-4 flex-shrink-0" />
              <span v-show="!isCollapsed" class="text-[13px] whitespace-nowrap">{{
                $t("navigation.organizations")
              }}</span>
              <span
                v-if="isCollapsed"
                class="invisible absolute left-full ml-2 rounded-md bg-gray-900 px-2 py-1 text-xs text-white opacity-0 transition-all group-hover:visible group-hover:opacity-100"
              >
                {{ $t("navigation.organizations") }}
              </span>
            </RouterLink>
          </li>
          <li v-show="isAdmin">
            <RouterLink
              to="/admin/settings"
              class="group relative flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100 hover:text-gray-900"
              :class="[
                { 'bg-gray-100 text-gray-900': isActive('/admin/settings') },
                isCollapsed ? 'justify-center' : ''
              ]"
              :title="isCollapsed ? $t('navigation.settings') : ''"
            >
              <SvgIcon name="settings" class="h-4 w-4 flex-shrink-0" />
              <span v-show="!isCollapsed" class="text-[13px] whitespace-nowrap">{{ $t("navigation.settings") }}</span>
              <span
                v-if="isCollapsed"
                class="invisible absolute left-full ml-2 rounded-md bg-gray-900 px-2 py-1 text-xs text-white opacity-0 transition-all group-hover:visible group-hover:opacity-100"
              >
                {{ $t("navigation.settings") }}
              </span>
            </RouterLink>
          </li>
        </ul>
      </nav>

      <!-- Toggle Button -->
      <div class="flex justify-center border-t border-gray-100 py-2">
        <button
          class="group relative flex h-7 w-7 items-center justify-center rounded-md text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600"
          :title="isCollapsed ? $t('navigation.expandSidebar') : $t('navigation.collapseSidebar')"
          @click="toggleSidebar"
        >
          <SvgIcon
            name="sidebar-toggle"
            class="h-3.5 w-3.5 transition-transform duration-150"
            :class="isCollapsed ? 'rotate-180' : ''"
          />
          <span
            v-if="isCollapsed"
            class="invisible absolute left-full ml-2 rounded-md bg-gray-900 px-2 py-1 text-xs text-white opacity-0 transition-all group-hover:visible group-hover:opacity-100"
          >
            {{ $t("navigation.expand") }}
          </span>
        </button>
      </div>

      <!-- User Section -->
      <div class="border-t border-gray-100 p-2.5">
        <div v-if="!isCollapsed" class="flex items-center gap-2.5 px-0.5">
          <div
            class="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-gray-200 text-xs font-medium text-gray-600"
          >
            {{
              userData?.first_name
                ? userData.first_name[0].toUpperCase()
                : userData?.email
                  ? userData.email[0].toUpperCase()
                  : "U"
            }}
          </div>
          <div class="flex-1 overflow-hidden">
            <p class="truncate text-[13px] font-medium text-gray-900">
              {{
                userData?.first_name || userData?.last_name
                  ? `${userData.first_name || ""} ${userData.last_name || ""}`.trim() || $t("navigation.user")
                  : $t("navigation.user")
              }}
            </p>
            <p class="truncate text-[11px] text-gray-500">{{ userData?.email || $t("navigation.loading") }}</p>
          </div>
        </div>
        <div v-else class="flex justify-center">
          <div
            class="flex h-8 w-8 items-center justify-center rounded-full bg-gray-200 text-xs font-medium text-gray-600"
          >
            {{
              userData?.first_name
                ? userData.first_name[0].toUpperCase()
                : userData?.email
                  ? userData.email[0].toUpperCase()
                  : "U"
            }}
          </div>
        </div>
        <div class="mt-2" :class="isCollapsed ? 'flex justify-center' : ''">
          <button
            type="button"
            class="group relative flex w-full items-center justify-center gap-1.5 rounded-md border border-gray-200 px-2.5 py-1.5 text-[13px] font-medium text-gray-700 transition-colors hover:bg-gray-50"
            :class="isCollapsed ? 'h-8 w-8 p-0' : 'w-full'"
            :title="isCollapsed ? $t('navigation.exit') : ''"
            @click="handleLogout"
          >
            <SvgIcon name="exit" class="h-3.5 w-3.5 flex-shrink-0" />
            <span v-show="!isCollapsed">{{ $t("navigation.exit") }}</span>
            <span
              v-if="isCollapsed"
              class="invisible absolute left-full ml-2 rounded-md bg-gray-900 px-2 py-1 text-xs text-white opacity-0 transition-all group-hover:visible group-hover:opacity-100"
            >
              {{ $t("navigation.exit") }}
            </span>
          </button>
        </div>
      </div>
    </aside>

    <!-- Main Content Area -->
    <main class="relative block flex-1 overflow-x-hidden overflow-y-auto px-6 py-6">
      <slot />
    </main>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { logout } from "@/utils/auth";
import SvgIcon from "@/components/SvgIcon.vue";
import { useCurrentUser } from "@/composables/useCurrentUser";

const { userData, isAdmin, loadUserData, clearUser } = useCurrentUser();

const route = useRoute();
const isCollapsed = ref(false);

onMounted(() => {
  loadUserData();
});

/**
 * Check if the given path is active
 */
function isActive(path: string): boolean {
  return route.path.startsWith(path);
}

/**
 * Toggle sidebar collapsed state
 */
function toggleSidebar(): void {
  isCollapsed.value = !isCollapsed.value;
}

/**
 * Handle logout - clear tokens and redirect to login
 */
async function handleLogout(): Promise<void> {
  clearUser();
  await logout();
}
</script>

<style scoped>
/* Sidebar styles */
</style>
