// web/src/components/field/inputs/DateInput.vue
<template>
  <div class="field-input-wrapper">
    <Input
      v-model="localValue"
      type="date"
      :placeholder="placeholder"
      :required="required"
      :readonly="readonly"
      :disabled="disabled"
      @blur="handleBlur"
    />
    <div v-if="dateFormat && formattedDisplay" class="mt-1 text-sm text-[--color-base-content]/70">
      {{ formattedDisplay }}
    </div>
    <div v-if="error" class="mt-1 text-sm text-[var(--color-error)]">{{ error }}</div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import Input from "@/components/ui/Input.vue";
import { formatDateByPattern } from "@/utils/time";

interface Props {
  modelValue?: string;
  dateFormat?: string;
  placeholder?: string;
  required?: boolean;
  readonly?: boolean;
  disabled?: boolean;
  error?: string;
}

interface Emits {
  (e: "update:modelValue", value: string): void;
  (e: "blur"): void;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: "",
  dateFormat: "",
  placeholder: "",
  required: false,
  readonly: false,
  disabled: false,
  error: ""
});

const emit = defineEmits<Emits>();
const localValue = ref(props.modelValue);

const formattedDisplay = computed(() => {
  if (!props.dateFormat || !localValue.value) return "";
  return formatDateByPattern(localValue.value, props.dateFormat);
});

watch(
  () => props.modelValue,
  (newValue) => {
    localValue.value = newValue || "";
  }
);

watch(localValue, (newValue) => {
  emit("update:modelValue", newValue || "");
});

function handleBlur(): void {
  emit("blur");
}
</script>

// web/site/src/lib/components/field/inputs/DateInput.svelte
<script lang="ts">
  import Input from "@/components/ui/Input.svelte";
  import { t } from "@/i18n/index.svelte";
  import { formatDateByPattern } from "@/utils/time";

  interface Props {
    value?: string;
    dateFormat?: string;
    placeholder?: string;
    required?: boolean;
    readonly?: boolean;
    disabled?: boolean;
    error?: string;
    onBlur?: () => void;
  }

  let {
    value = $bindable(""),
    dateFormat = "",
    placeholder = "",
    required = false,
    readonly = false,
    disabled = false,
    error = "",
    onBlur
  }: Props = $props();

  const formattedDisplay = $derived.by(() => {
    if (!dateFormat || !value) {
      return "";
    }
    return formatDateByPattern(value, dateFormat);
  });

  function setToday(): void {
    const now = new Date();
    const month = String(now.getMonth() + 1).padStart(2, "0");
    const day = String(now.getDate()).padStart(2, "0");
    value = `${now.getFullYear()}-${month}-${day}`;
    onBlur?.();
  }

  function handleBlur(): void {
    onBlur?.();
  }
</script>

<div class="field-input-wrapper">
  <div class="flex items-center gap-2">
    <div class="min-w-0 flex-1">
      <Input bind:value type="date" {placeholder} {required} {readonly} {disabled} onblur={handleBlur} />
    </div>
    {#if !readonly && !disabled}
      <button type="button" class="btn btn-ghost btn-sm whitespace-nowrap" onclick={setToday}>
        {t("signing.setToday")}
      </button>
    {/if}
  </div>
  {#if dateFormat && formattedDisplay}
    <div class="mt-1 text-sm text-[--color-base-content]/70">
      {formattedDisplay}
    </div>
  {/if}
  {#if error}
    <div class="mt-1 text-sm text-[var(--color-error)]">{error}</div>
  {/if}
</div>
