// web/private/src/lib/components/template/Page.svelte
<script lang="ts">
  import { tick } from "svelte";
  import FieldArea from "@/components/template/Area.svelte";
  import type { PreviewImages } from "@/models/index";
  import type { Area, Field } from "@/models/template";

  type PageImage = PreviewImages & { url?: string };

  interface AreaItem {
    area: Area;
    field: Field;
  }

  interface Props {
    image: PageImage;
    areas?: AreaItem[];
    defaultFields?: Field[];
    allowDraw?: boolean;
    drawField?: Field | null;
    editable?: boolean;
    isDrag?: boolean;
    number: number;
    onDraw?: (area: Area) => void;
    onDropField?: (event: Record<string, unknown>) => void;
    onRemoveArea?: (area: Area) => void;
    onSelectSubmitter?: (submitterId: string) => void;
  }

  let {
    image,
    areas = [],
    defaultFields = [],
    allowDraw = true,
    drawField = null,
    editable = true,
    isDrag = false,
    number,
    onDraw,
    onDropField,
    onRemoveArea,
    onSelectSubmitter
  }: Props = $props();

  // Writable derived: reset when the area count changes; bind:this fills the slots in between
  let areaRefEls: Array<ReturnType<typeof FieldArea> | undefined> = $derived(new Array(areas.length));
  let isMove = $state(false);
  let resizeDirection = $state<string | null>(null);
  let newArea = $state<Area | null>(null);
  let mask = $state<HTMLDivElement | null>(null);
  let imageEl = $state<HTMLImageElement | null>(null);

  const width = $derived(image.metadata.width);
  const height = $derived(image.metadata.height);

  export { areaRefEls as areaRefs, mask };

  function onImageLoad(e: Event): void {
    const target = e.target as HTMLImageElement;
    target.setAttribute("width", target.naturalWidth.toString());
    target.setAttribute("height", target.naturalHeight.toString());
  }

  function onDrop(e: DragEvent): void {
    e.preventDefault();
    if (!mask) {
      return;
    }

    const rect = mask.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    onDropField?.({
      x,
      y,
      maskW: mask.clientWidth,
      maskH: mask.clientHeight,
      page: number
    });
  }

  function onStartDraw(e: PointerEvent): void {
    if (!allowDraw || !drawField || !editable || !mask) {
      return;
    }

    tick().then(() => {
      if (!mask) {
        return;
      }

      const initialX = e.layerX / mask.clientWidth;
      const initialY = e.layerY / mask.clientHeight;

      newArea = {
        initialX,
        initialY,
        x: initialX,
        y: initialY,
        w: 0,
        h: 0,
        page: number,
        attachment_id: ""
      };
    });
  }

  function onPointermove(e: PointerEvent): void {
    if (!newArea || !mask) {
      return;
    }

    const dx = e.layerX / mask.clientWidth - (newArea.initialX || 0);
    const dy = e.layerY / mask.clientHeight - (newArea.initialY || 0);

    newArea.x = dx > 0 ? newArea.initialX || 0 : e.layerX / mask.clientWidth;
    newArea.y = dy > 0 ? newArea.initialY || 0 : e.layerY / mask.clientHeight;

    if (drawField?.type === "cells") {
      newArea.cell_w = newArea.h * (mask.clientHeight / mask.clientWidth);
    }

    newArea.w = Math.abs(dx);
    newArea.h = Math.abs(dy);
  }

  function onPointerup(): void {
    if (newArea) {
      const area: Area = {
        x: newArea.x,
        y: newArea.y,
        w: newArea.w,
        h: newArea.h,
        page: number, // This is 0-based index (0 = first page, 1 = second page, etc.)
        attachment_id: ""
      };

      if (newArea.cell_w) {
        area.cell_w = newArea.cell_w;
        // Persist cell count for signing page (same formula as Area.vue)
        const cw = newArea.cell_w;
        const aw = newArea.w;
        if (cw > 0 && aw > 0) {
          let currentWidth = 0;
          let count = 0;
          while (currentWidth + (cw + cw / 4) < aw) {
            currentWidth += cw;
            count++;
          }
          area.cell_count = Math.max(count, 1);
        }
      }

      // Ensure page number is explicitly set
      onDraw?.({ ...area, page: number });
    }

    newArea = null;
  }
</script>

<div class="relative cursor-crosshair select-none" style={drawField ? "touch-action: none" : ""}>
  <img
    bind:this={imageEl}
    loading="lazy"
    src={`${image.url}/${image.filename}`}
    alt="Page {number + 1}"
    {width}
    {height}
    class="mb-4 rounded border border-[#e7e2df]"
    onload={onImageLoad}
  />
  <div class="absolute top-0 right-0 bottom-0 left-0" role="presentation" onpointerdown={onStartDraw}>
    {#each areas as item, i (i)}
      <FieldArea
        bind:this={areaRefEls[i]}
        area={item.area}
        field={item.field}
        {editable}
        defaultField={defaultFields.find((f) => f.name === item.field.name)}
        onStartResize={(direction) => {
          resizeDirection = direction;
        }}
        onStopResize={() => {
          resizeDirection = null;
        }}
        onStartDrag={() => {
          isMove = true;
        }}
        onStopDrag={() => {
          isMove = false;
        }}
        onRemove={() => onRemoveArea?.(item.area)}
        {onSelectSubmitter}
      />
    {/each}
    {#if newArea && drawField}
      <FieldArea isDraw={true} field={drawField} area={newArea} />
    {/if}
  </div>
  <div
    style:display={resizeDirection || isMove || isDrag || newArea || drawField ? null : "none"}
    id="mask"
    bind:this={mask}
    role="presentation"
    class="absolute top-0 right-0 bottom-0 left-0 z-10 {isDrag || isMove ? 'cursor-grab' : ''} {drawField ||
    resizeDirection === 'nwse'
      ? 'cursor-nwse-resize'
      : ''} {resizeDirection === 'ew' ? 'cursor-ew-resize' : ''}"
    onpointermove={onPointermove}
    onpointerdown={onStartDraw}
    ondragover={(e) => e.preventDefault()}
    ondrop={onDrop}
    onpointerup={onPointerup}
  ></div>
</div>

// web/src/components/template/Page.vue
<template>
  <div class="relative cursor-crosshair select-none" :style="drawField ? 'touch-action: none' : ''">
    <img
      ref="imageEl"
      loading="lazy"
      :src="`${props.image.url}/${props.image.filename}`"
      :width="width"
      :height="height"
      class="mb-4 rounded border border-[#e7e2df]"
      @load="onImageLoad"
    />
    <div class="absolute top-0 right-0 bottom-0 left-0" @pointerdown="onStartDraw">
      <FieldArea
        v-for="(item, i) in areas"
        :key="i"
        :ref="setAreaRefs"
        :area="item.area"
        :field="item.field"
        :editable="editable"
        :default-field="defaultFields.find((f) => f.name === item.field.name)"
        @start-resize="resizeDirection = $event"
        @stop-resize="resizeDirection = null"
        @start-drag="isMove = true"
        @stop-drag="isMove = false"
        @remove="$emit('remove-area', item.area)"
        @select-submitter="$emit('select-submitter', $event)"
      />
      <FieldArea v-if="newArea && drawField" :is-draw="true" :field="drawField" :area="newArea" />
    </div>
    <div
      v-show="resizeDirection || isMove || isDrag || newArea || drawField"
      id="mask"
      ref="mask"
      class="absolute top-0 right-0 bottom-0 left-0 z-10"
      :class="{
        'cursor-grab': isDrag || isMove,
        'cursor-nwse-resize': drawField || resizeDirection === 'nwse',
        'cursor-ew-resize': resizeDirection === 'ew'
      }"
      @pointermove="onPointermove"
      @pointerdown="onStartDraw"
      @dragover.prevent
      @drop="onDrop"
      @pointerup="onPointerup"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUpdate, ref } from "vue";
import type { PreviewImages, Submitters } from "@/models/index";
import type { Area, Field } from "@/models/template";
import FieldArea from "@/components/template/Area.vue";

interface Props {
  image: PreviewImages;
  areas?: any[];
  defaultFields?: Field[];
  allowDraw?: boolean;
  selectedSubmitter: Submitters;
  drawField?: Field | null;
  editable?: boolean;
  isDrag?: boolean;
  number: number;
}

const props = withDefaults(defineProps<Props>(), {
  areas: () => [],
  defaultFields: () => [],
  allowDraw: true,
  drawField: null,
  editable: true,
  isDrag: false
});

interface Emits {
  draw: [area: Area];
  "drop-field": [event: any];
  "remove-area": [area: Area];
  "select-submitter": [submitterId: string];
}

const emit = defineEmits<Emits>();

const areaRefs = ref<any[]>([]);
const isMove = ref(false);
const resizeDirection = ref<string | null>(null);
const newArea = ref<Area | null>(null);
const mask = ref<HTMLDivElement | null>(null);
const imageEl = ref<HTMLImageElement | null>(null);

const width = computed(() => props.image.metadata.width);
const height = computed(() => props.image.metadata.height);

onBeforeUpdate(() => {
  areaRefs.value = [];
});

function onImageLoad(e: Event): void {
  const target = e.target as HTMLImageElement;
  target.setAttribute("width", target.naturalWidth.toString());
  target.setAttribute("height", target.naturalHeight.toString());
}

function setAreaRefs(el: any): void {
  if (el) {
    areaRefs.value.push(el);
  }
}

function onDrop(e: DragEvent): void {
  e.preventDefault();
  if (!mask.value) {
    return;
  }

  const rect = mask.value.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const y = e.clientY - rect.top;

  emit("drop-field", {
    x,
    y,
    maskW: mask.value.clientWidth,
    maskH: mask.value.clientHeight,
    page: props.number
  });
}

function onStartDraw(e: PointerEvent): void {
  if (!props.allowDraw || !props.drawField || !props.editable || !mask.value) {
    return;
  }

  nextTick(() => {
    if (!mask.value) {
      return;
    }

    const initialX = e.layerX / mask.value.clientWidth;
    const initialY = e.layerY / mask.value.clientHeight;

    newArea.value = {
      initialX,
      initialY,
      x: initialX,
      y: initialY,
      w: 0,
      h: 0,
      page: props.number,
      attachment_id: ""
    };
  });
}

function onPointermove(e: PointerEvent): void {
  if (!newArea.value || !mask.value) {
    return;
  }

  const dx = e.layerX / mask.value.clientWidth - (newArea.value.initialX || 0);
  const dy = e.layerY / mask.value.clientHeight - (newArea.value.initialY || 0);

  newArea.value.x = dx > 0 ? newArea.value.initialX || 0 : e.layerX / mask.value.clientWidth;
  newArea.value.y = dy > 0 ? newArea.value.initialY || 0 : e.layerY / mask.value.clientHeight;

  if (props.drawField?.type === "cells") {
    newArea.value.cell_w = newArea.value.h * (mask.value.clientHeight / mask.value.clientWidth);
  }

  newArea.value.w = Math.abs(dx);
  newArea.value.h = Math.abs(dy);
}

function onPointerup(): void {
  if (newArea.value) {
    const area: Area = {
      x: newArea.value.x,
      y: newArea.value.y,
      w: newArea.value.w,
      h: newArea.value.h,
      page: props.number, // This is 0-based index (0 = first page, 1 = second page, etc.)
      attachment_id: ""
    };

    if (newArea.value.cell_w) {
      area.cell_w = newArea.value.cell_w;
      // Persist cell count for signing page (same formula as Area.vue)
      const cw = newArea.value.cell_w;
      const aw = newArea.value.w;
      if (cw > 0 && aw > 0) {
        let currentWidth = 0;
        let count = 0;
        while (currentWidth + (cw + cw / 4) < aw) {
          currentWidth += cw;
          count++;
        }
        area.cell_count = Math.max(count, 1);
      }
    }

    // Ensure page number is explicitly set
    emit("draw", { ...area, page: props.number });
  }

  newArea.value = null;
}

defineExpose({
  areaRefs
});
</script>
