// web/src/components/ui/Card.vue
<template>
  <div class="rounded-lg border border-[var(--color-base-300)] bg-[var(--color-base-100)]">
    <div v-if="$slots.header" class="border-b border-[var(--color-base-300)] px-6 py-5">
      <slot name="header" />
    </div>
    <div class="px-6 py-5">
      <slot />
    </div>
    <div v-if="$slots.footer" class="border-t border-[var(--color-base-300)] bg-[var(--color-base-200)]/30 px-6 py-4">
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup lang="ts">
// Simple card component with header, body, and footer slots
</script>

// web2/src/lib/components/ui/Card.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    header?: Snippet;
    footer?: Snippet;
    children?: Snippet;
  }

  let { header, footer, children }: Props = $props();
</script>

<!-- Simple card component with header, body, and footer slots -->
<div class="rounded-lg border border-[var(--color-base-300)] bg-[var(--color-base-100)]">
  {#if header}
    <div class="border-b border-[var(--color-base-300)] px-6 py-5">
      {@render header()}
    </div>
  {/if}
  <div class="px-6 py-5">
    {@render children?.()}
  </div>
  {#if footer}
    <div class="border-t border-[var(--color-base-300)] bg-[var(--color-base-200)]/30 px-6 py-4">
      {@render footer()}
    </div>
  {/if}
</div>
