// web/src/components/ui/Label.vue
<template>
  <label :class="labelClasses">
    <slot />
    <span v-if="required" class="ml-1 text-[var(--color-error)]">*</span>
  </label>
</template>

<script setup lang="ts">
import { computed } from "vue";

interface Props {
  required?: boolean;
}

withDefaults(defineProps<Props>(), {
  required: false
});

const labelClasses = computed(() => {
  return "block text-sm font-medium text-gray-700 mb-1";
});
</script>

// web2/src/lib/components/ui/Label.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    required?: boolean;
    children?: Snippet;
  }

  let { required = false, children }: Props = $props();

  const labelClasses = "block text-sm font-medium text-gray-700 mb-1";
</script>

<label class={labelClasses}>
  {@render children?.()}
  {#if required}
    <span class="ml-1 text-[var(--color-error)]">*</span>
  {/if}
</label>
