// web/private/src/lib/components/common/FormModal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import Modal from "@/components/ui/Modal.svelte";
  import Button from "@/components/ui/Button.svelte";

  interface Props {
    open: boolean;
    title: string;
    size?: "sm" | "md" | "lg" | "xl";
    submitText?: string;
    cancelText?: string;
    showCancel?: boolean;
    closeButton?: boolean;
    closeOnOutsideClick?: boolean;
    closeOnEscape?: boolean;
    validateOnMount?: boolean;
    onSubmit?: (formData: Record<string, unknown>) => void | Promise<void>;
    onSubmitEvent?: (formData: Record<string, unknown>) => void;
    onCancel?: () => void;
    onClose?: () => void;
    children?: Snippet<[formData: Record<string, any>, errors: Record<string, string>]>;
    footer?: Snippet<[submit: () => void, cancel: () => void, isSubmitting: boolean]>;
  }

  let {
    open: isOpen = $bindable(),
    title,
    size = "md",
    submitText = "Submit",
    cancelText = "Cancel",
    showCancel = true,
    closeButton = true,
    closeOnOutsideClick = true,
    closeOnEscape = true,
    validateOnMount = false,
    onSubmit,
    onSubmitEvent,
    onCancel,
    onClose,
    children: formChildren,
    footer: footerSnippet
  }: Props = $props();

  let formData = $state<Record<string, any>>({});
  let errors = $state<Record<string, string>>({});
  let isSubmitting = $state(false);

  const formIsValid = $derived(Object.keys(errors).length === 0);

  $effect(() => {
    if (isOpen) {
      if (validateOnMount) {
        validateForm();
      }
      // Initialize formData when modal opens
      // Initialize formData with default values if empty
      // Individual fields will be initialized by v-model in the template
      if (!formData.name) {
        formData.name = "";
      }
      if (!formData.email) {
        formData.email = "";
      }
      if (!formData.role) {
        formData.role = "member";
      }
    } else {
      // Reset form when modal closes
      resetForm();
    }
  });

  function handleClose(): void {
    if (!isSubmitting) {
      isOpen = false;
      onClose?.();
      onCancel?.();
      resetForm();
    }
  }

  async function handleSubmit(): Promise<void> {
    if (isSubmitting || !formIsValid) {
      return;
    }

    validateForm();

    if (!formIsValid) {
      return;
    }

    isSubmitting = true;

    try {
      if (onSubmit) {
        const result = onSubmit(formData);
        // If we got a Promise, wait for it, then reset the submitting state.
        // For sync handlers, keep isSubmitting true: the parent closes the
        // modal or resets it on success/error, preserving the loading state.
        if (result instanceof Promise) {
          await result;
          isSubmitting = false;
        }
      } else {
        // Emit submit event - parent handler should handle async operations
        onSubmitEvent?.(formData);
      }
    } catch (error) {
      // Re-throw error so parent component can handle it
      console.error("FormModal submit error:", error);
      isSubmitting = false;
      throw error;
    }
  }

  // Expose method to reset submitting state (for parent components)
  export function resetSubmitting(): void {
    isSubmitting = false;
  }

  export function validateForm(): void {
    errors = {};
  }

  export function resetForm(): void {
    formData = {};
    errors = {};
  }

  export function setFormData(data: Record<string, unknown>): void {
    formData = { ...data };
  }

  export function getFormData(): Record<string, any> {
    return formData;
  }

  export function setError(field: string, message: string): void {
    errors[field] = message;
  }

  export function clearError(field: string): void {
    const { [field]: _removed, ...rest } = errors;
    errors = rest;
  }

  export function clearAllErrors(): void {
    errors = {};
  }

  export function open(): void {
    isOpen = true;
  }

  export function close(): void {
    handleClose();
  }

  export function isValid(): boolean {
    return formIsValid;
  }
</script>

<Modal
  bind:open={isOpen}
  {title}
  {size}
  showClose={closeButton}
  closeOnBackdrop={closeOnOutsideClick}
  {closeOnEscape}
  onClose={handleClose}
>
  <div>
    {@render formChildren?.(formData, errors)}
  </div>

  {#snippet footer()}
    {#if footerSnippet}
      {@render footerSnippet(handleSubmit, handleClose, isSubmitting)}
    {:else}
      <div class="flex justify-end gap-3">
        {#if showCancel}
          <Button variant="ghost" disabled={isSubmitting} onclick={handleClose}>
            {cancelText}
          </Button>
        {/if}
        <Button variant="primary" loading={isSubmitting} disabled={isSubmitting || !formIsValid} onclick={handleSubmit}>
          {submitText}
        </Button>
      </div>
    {/if}
  {/snippet}
</Modal>

// web/src/components/common/FormModal.vue
<template>
  <Modal
    v-model="isOpen"
    :title="title"
    :size="size"
    :show-close="closeButton"
    :close-on-backdrop="closeOnOutsideClick"
    :close-on-escape="closeOnEscape"
    @close="handleClose"
  >
    <template #default>
      <div class="py-4">
        <slot :form-data="formData" :errors="errors" />
      </div>
    </template>

    <template #footer>
      <slot name="footer" :submit="handleSubmit" :cancel="handleClose" :is-submitting="isSubmitting">
        <div class="flex justify-end gap-3">
          <Button v-if="showCancel" variant="ghost" :disabled="isSubmitting" @click="handleClose">
            {{ cancelText }}
          </Button>
          <Button variant="primary" :loading="isSubmitting" :disabled="isSubmitting || !isValid" @click="handleSubmit">
            {{ submitText }}
          </Button>
        </div>
      </slot>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import Modal from "@/components/ui/Modal.vue";
import Button from "@/components/ui/Button.vue";

interface Props {
  modelValue: boolean;
  title: string;
  size?: "sm" | "md" | "lg" | "xl";
  submitText?: string;
  cancelText?: string;
  showCancel?: boolean;
  closeButton?: boolean;
  closeOnOutsideClick?: boolean;
  closeOnEscape?: boolean;
  validateOnMount?: boolean;
  onSubmit?: (formData: Record<string, unknown>) => void | Promise<void>;
}

interface Emits {
  (e: "update:modelValue", value: boolean): void;
  (e: "submit", formData: Record<string, unknown>): void;
  (e: "cancel" | "close"): void;
}

const props = withDefaults(defineProps<Props>(), {
  size: "md",
  submitText: "Submit",
  cancelText: "Cancel",
  showCancel: true,
  closeButton: true,
  closeOnOutsideClick: true,
  closeOnEscape: true,
  validateOnMount: false,
  onSubmit: undefined
});

const emit = defineEmits<Emits>();

const formData = ref<Record<string, any>>({});
const errors = ref<Record<string, string>>({});
const isSubmitting = ref(false);

const isOpen = computed({
  get: () => props.modelValue,
  set: (value) => emit("update:modelValue", value)
});

const isValid = computed(() => {
  return Object.keys(errors.value).length === 0;
});

watch(isOpen, (newValue) => {
  if (newValue && props.validateOnMount) {
    validateForm();
  }
  // Initialize formData when modal opens
  if (newValue) {
    // Initialize formData with default values if empty
    // Individual fields will be initialized by v-model in the template
    if (!formData.value.name) {
      formData.value.name = "";
    }
    if (!formData.value.email) {
      formData.value.email = "";
    }
    if (!formData.value.role) {
      formData.value.role = "member";
    }
  } else {
    // Reset form when modal closes
    resetForm();
  }
});

function handleClose(): void {
  if (!isSubmitting.value) {
    isOpen.value = false;
    emit("close");
    emit("cancel");
    resetForm();
  }
}

async function handleSubmit(): Promise<void> {
  if (isSubmitting.value || !isValid.value) {
    return;
  }

  validateForm();

  if (!isValid.value) {
    return;
  }

  isSubmitting.value = true;

  try {
    if (props.onSubmit) {
      const result = props.onSubmit(formData.value);
      // If we got a Promise, wait for it, then reset the submitting state.
      // For sync handlers, keep isSubmitting true: the parent closes the
      // modal or resets it on success/error, preserving the loading state.
      if (result instanceof Promise) {
        await result;
        isSubmitting.value = false;
      }
    } else {
      // Emit submit event - parent handler should handle async operations
      emit("submit", formData.value);
    }
  } catch (error) {
    // Re-throw error so parent component can handle it
    console.error("FormModal submit error:", error);
    isSubmitting.value = false;
    throw error;
  }
}

// Expose method to reset submitting state (for parent components)
function resetSubmitting(): void {
  isSubmitting.value = false;
}

function validateForm(): void {
  errors.value = {};
}

function resetForm(): void {
  formData.value = {};
  errors.value = {};
}

function setFormData(data: Record<string, unknown>): void {
  formData.value = { ...data };
}

function setError(field: string, message: string): void {
  errors.value[field] = message;
}

function clearError(field: string): void {
  const { [field]: _removed, ...rest } = errors.value;
  errors.value = rest;
}

function clearAllErrors(): void {
  errors.value = {};
}

defineExpose({
  open: () => {
    isOpen.value = true;
  },
  close: handleClose,
  setFormData,
  getFormData: () => formData.value,
  setError,
  clearError,
  clearAllErrors,
  resetForm,
  validateForm,
  isValid: () => isValid.value,
  resetSubmitting
});
</script>
