// web2/src/lib/components/common/LanguageSwitcher.svelte
<script lang="ts">
  import Select from "@/components/ui/Select.svelte";
  import { getLocale, setLocale, SUPPORTED_LOCALES, type Locale } from "@/i18n/index.svelte";
  import { apiPut } from "@/services/api";

  const locales = SUPPORTED_LOCALES;

  async function changeLocale(newLocale: string): Promise<void> {
    if (!newLocale || newLocale === getLocale()) {
      return;
    }

    // Update locale immediately for instant UI change
    setLocale(newLocale as Locale);
    localStorage.setItem("locale", newLocale);
    document.documentElement.setAttribute("lang", newLocale);

    // Update user preference on backend (non-blocking)
    try {
      await apiPut("/api/v1/i18n/user/locale", { locale: newLocale });
    } catch (error) {
      // Silently fail - locale is already updated in frontend
      // User can still use the app even if backend update fails
      console.warn("Failed to update user locale on server:", error);
    }
  }

  function handleChange(event: Event): void {
    const value = (event.currentTarget as HTMLSelectElement).value;
    if (value && value !== getLocale()) {
      changeLocale(value);
    }
  }
</script>

<Select class="language-switcher" value={getLocale()} onchange={handleChange}>
  {#each Object.entries(locales) as [code, name] (code)}
    <option value={code}>{name}</option>
  {/each}
</Select>

<style>
  :global(.language-switcher) {
    min-width: 120px;
  }
</style>

// web/src/components/common/LanguageSwitcher.vue
<template>
  <Select v-model="currentLocale" class="language-switcher">
    <option v-for="(name, code) in locales" :key="code" :value="code">
      {{ name }}
    </option>
  </Select>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { SUPPORTED_LOCALES } from '@/i18n'
import { apiPut } from '@/services/api'
import Select from '@/components/ui/Select.vue'

const { locale } = useI18n()
const locales = SUPPORTED_LOCALES

const currentLocale = computed({
  get: () => locale.value as string,
  set: (value: string) => {
    if (value && value !== locale.value) {
      changeLocale(value)
    }
  }
})

async function changeLocale(newLocale: string) {
  if (!newLocale || newLocale === locale.value) {
    return
  }
  
  // Update locale immediately for instant UI change
  locale.value = newLocale
  localStorage.setItem('locale', newLocale)
  document.documentElement.setAttribute('lang', newLocale)
  
  // Update user preference on backend (non-blocking)
  try {
    await apiPut('/api/v1/i18n/user/locale', { locale: newLocale })
  } catch (error) {
    // Silently fail - locale is already updated in frontend
    // User can still use the app even if backend update fails
    console.warn('Failed to update user locale on server:', error)
  }
}
</script>

<style scoped>
.language-switcher {
  min-width: 120px;
}
</style>
