// web/src/components/ui/Checkbox.vue
<template>
  <input
    type="checkbox"
    :class="checkboxClasses"
    :checked="isChecked"
    v-bind="restAttrs"
    @change="onChange"
  />
</template>

<script setup lang="ts">
import { computed, useAttrs } from "vue";

interface Props {
  modelValue?: boolean | string[];
  value?: string;
  size?: "sm" | "md";
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: false,
  value: undefined,
  size: "md"
});

const emit = defineEmits<{ (e: "update:modelValue", value: boolean | string[]): void }>();

const attrs = useAttrs();
const restAttrs = computed(() => {
  const { modelValue: _mv, value: _v, ...rest } = attrs as Record<string, unknown>;
  return rest;
});

const isChecked = computed(() => {
  if (props.value !== undefined && props.value !== "") {
    const arr = Array.isArray(props.modelValue) ? props.modelValue : [];
    return arr.includes(props.value);
  }
  return props.modelValue === true;
});

function onChange(e: Event): void {
  const target = e.target as HTMLInputElement;
  if (props.value !== undefined && props.value !== "") {
    const arr = Array.isArray(props.modelValue) ? [...props.modelValue] : [];
    const i = arr.indexOf(props.value);
    if (target.checked) {
      if (i === -1) arr.push(props.value);
    } else {
      if (i !== -1) arr.splice(i, 1);
    }
    emit("update:modelValue", arr);
  } else {
    emit("update:modelValue", target.checked);
  }
}

const checkboxClasses = computed(() => {
  const base =
    "rounded border-gray-300 text-[var(--color-primary)] focus:ring-[var(--color-primary)] focus:ring-2 transition-colors cursor-pointer";

  const sizes = {
    sm: "h-4 w-4",
    md: "h-5 w-5"
  };

  const disabled = "$attrs.disabled" in ["", true] ? "opacity-50 cursor-not-allowed" : "";

  return [base, sizes[props.size], disabled].filter(Boolean).join(" ");
});
</script>

// web/private/src/lib/components/ui/Checkbox.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";

  interface Props extends Omit<HTMLInputAttributes, "checked" | "value" | "size" | "type"> {
    checked?: boolean | string[];
    value?: string;
    size?: "sm" | "md";
  }

  let { checked = $bindable(false), value, size = "md", ...rest }: Props = $props();

  const isChecked = $derived.by(() => {
    if (value !== undefined && value !== "") {
      const arr = Array.isArray(checked) ? checked : [];
      return arr.includes(value);
    }
    return checked === true;
  });

  function onChange(e: Event): void {
    const target = e.target as HTMLInputElement;
    if (value !== undefined && value !== "") {
      const arr = Array.isArray(checked) ? [...checked] : [];
      const i = arr.indexOf(value);
      if (target.checked) {
        if (i === -1) {
          arr.push(value);
        }
      } else {
        if (i !== -1) {
          arr.splice(i, 1);
        }
      }
      checked = arr;
    } else {
      checked = target.checked;
    }
  }
</script>

<input type="checkbox" class="ui-checkbox ui-checkbox-{size}" checked={isChecked} onchange={onChange} {...rest} />

<style>
  .ui-checkbox {
    accent-color: var(--base-hlt-invert);
    border-radius: var(--radius-4);
    cursor: pointer;
    transition: var(--transition-colors);
  }
  .ui-checkbox:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .ui-checkbox:focus-visible {
    outline: none;
    box-shadow: var(--shadow-focus);
  }
  .ui-checkbox-sm {
    width: 14px;
    height: 14px;
  }
  .ui-checkbox-md {
    width: 16px;
    height: 16px;
  }
</style>
