// web2/src/lib/components/field/inputs/FileInput.svelte
<script lang="ts">
  import FileDropZone from "@/components/ui/FileDropZone.svelte";

  interface Props {
    value?: string;
    type?: "file" | "image";
    disabled?: boolean;
    error?: string;
    onBlur?: () => void;
  }

  let { value = $bindable(""), type = "file", disabled = false, error = "", onBlur }: Props = $props();

  let selectedFileName = $state("");

  const accept = $derived(type === "image" ? "image/*" : undefined);

  $effect(() => {
    if (!value || value === "") {
      selectedFileName = "";
    }
  });

  function handleFileChange(file: File): void {
    selectedFileName = file.name;

    if (type === "image") {
      const reader = new FileReader();
      reader.onload = (e) => {
        const result = e.target?.result as string;
        if (result) {
          value = result;
        }
        onBlur?.();
      };
      reader.readAsDataURL(file);
    } else {
      value = file.name;
      onBlur?.();
    }
  }

  function handleClear(): void {
    selectedFileName = "";
    value = "";
    onBlur?.();
  }
</script>

<div class="field-input-wrapper">
  <FileDropZone
    {accept}
    {disabled}
    selectedLabel={selectedFileName}
    onChange={handleFileChange}
    onClear={handleClear}
  />
  {#if type === "image" && value}
    <div class="mt-2 rounded-md border border-[var(--color-base-300)] bg-[--color-base-100] p-2">
      <img src={value} alt="" class="max-h-32 w-full object-contain" />
    </div>
  {/if}
  {#if error}
    <div class="mt-2 text-sm text-[var(--color-error)]">{error}</div>
  {/if}
</div>

// web/src/components/field/inputs/FileInput.vue
<template>
  <div class="field-input-wrapper">
    <FileDropZone
      :accept="accept"
      :disabled="disabled"
      :selected-label="selectedFileName"
      @change="handleFileChange"
      @clear="handleClear"
    />
    <div v-if="type === 'image' && modelValue" class="mt-2 rounded-md border border-[var(--color-base-300)] bg-[--color-base-100] p-2">
      <img :src="modelValue" alt="" class="max-h-32 w-full object-contain" />
    </div>
    <div v-if="error" class="mt-2 text-sm text-[var(--color-error)]">{{ error }}</div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import FileDropZone from "@/components/ui/FileDropZone.vue";

interface Props {
  modelValue?: string;
  type?: "file" | "image";
  placeholder?: string;
  required?: boolean;
  readonly?: boolean;
  disabled?: boolean;
  error?: string;
}

interface Emits {
  (e: "update:modelValue", value: string): void;
  (e: "blur"): void;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: "",
  type: "file",
  placeholder: "",
  required: false,
  readonly: false,
  disabled: false,
  error: ""
});

const emit = defineEmits<Emits>();
const selectedFileName = ref("");

const accept = props.type === "image" ? "image/*" : undefined;

watch(
  () => props.modelValue,
  (newValue) => {
    if (!newValue || newValue === "") {
      selectedFileName.value = "";
    }
  }
);

function handleFileChange(file: File): void {
  selectedFileName.value = file.name;

  if (props.type === "image") {
    const reader = new FileReader();
    reader.onload = (e) => {
      const result = e.target?.result as string;
      if (result) emit("update:modelValue", result);
      emit("blur");
    };
    reader.readAsDataURL(file);
  } else {
    emit("update:modelValue", file.name);
    emit("blur");
  }
}

function handleClear(): void {
  selectedFileName.value = "";
  emit("update:modelValue", "");
  emit("blur");
}
</script>
