// web/src/components/field/inputs/TextInput.vue
<template>
  <div class="field-input-wrapper">
    <Input
      v-model="localValue"
      :type="inputType"
      :placeholder="placeholder"
      :required="required"
      :readonly="readonly"
      :disabled="disabled"
      :min="min"
      :max="max"
      :step="step"
      @blur="handleBlur"
    />
    <div v-if="error" class="mt-1 text-sm text-[var(--color-error)]">{{ error }}</div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import Input from "@/components/ui/Input.vue";

interface Props {
  modelValue?: string;
  type?: string;
  placeholder?: string;
  required?: boolean;
  readonly?: boolean;
  disabled?: boolean;
  error?: string;
  min?: number | string;
  max?: number | string;
  step?: string;
}

interface Emits {
  (e: "update:modelValue", value: string): void;
  (e: "blur"): void;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: "",
  type: "text",
  placeholder: "",
  required: false,
  readonly: false,
  disabled: false,
  error: "",
  min: undefined,
  max: undefined,
  step: undefined
});

const emit = defineEmits<Emits>();
const localValue = ref(props.modelValue);

const inputType = computed(() => {
  if (props.type === "number") {
    return "number";
  }
  if (props.type === "phone") {
    return "tel";
  }
  return "text";
});

watch(
  () => props.modelValue,
  (newValue) => {
    localValue.value = newValue || "";
  }
);

watch(localValue, (newValue) => {
  emit("update:modelValue", newValue || "");
});

function handleBlur(): void {
  emit("blur");
}
</script>

// web/private/src/lib/components/field/inputs/TextInput.svelte
<script lang="ts">
  import Input from "@/components/ui/Input.svelte";

  interface Props {
    value?: string;
    type?: string;
    placeholder?: string;
    required?: boolean;
    readonly?: boolean;
    disabled?: boolean;
    error?: string;
    min?: number | string;
    max?: number | string;
    step?: string;
    class?: string;
    onBlur?: () => void;
  }

  let {
    value = $bindable(""),
    type = "text",
    placeholder = "",
    required = false,
    readonly = false,
    disabled = false,
    error = "",
    min,
    max,
    step,
    class: className = "",
    onBlur
  }: Props = $props();

  const inputType = $derived.by(() => {
    if (type === "number") {
      return "number" as const;
    }
    if (type === "phone") {
      return "tel" as const;
    }
    return "text" as const;
  });

  function handleBlur(): void {
    onBlur?.();
  }
</script>

<div class="field-input-wrapper {className}">
  <Input
    bind:value
    type={inputType}
    {placeholder}
    {required}
    {readonly}
    {disabled}
    {min}
    {max}
    {step}
    onblur={handleBlur}
  />
  {#if error}
    <div class="mt-1 text-sm text-[var(--color-error)]">{error}</div>
  {/if}
</div>
