// web/private/src/lib/components/field/Contenteditable.svelte
<script lang="ts">
  import SvgIcon from "@/components/SvgIcon.svelte";

  interface Props {
    value?: string;
    iconInline?: boolean;
    iconWidth?: number;
    withRequired?: boolean;
    selectOnEditClick?: boolean;
    editable?: boolean;
    iconStrokeWidth?: number;
    onFocus?: (event: FocusEvent) => void;
    onBlur?: (event: FocusEvent) => void;
    onValueChange?: (value: string) => void;
    class?: string;
    style?: string;
  }

  let {
    value = $bindable(""),
    iconInline = false,
    iconWidth = 30,
    withRequired = false,
    selectOnEditClick = false,
    editable = true,
    iconStrokeWidth = 2,
    onFocus,
    onBlur,
    onValueChange,
    class: className = "",
    style
  }: Props = $props();

  let contenteditableEl: HTMLSpanElement | null = $state(null);
  // Writable derived: resets to the incoming prop, still locally assignable (Vue: ref + watch)
  let internalValue = $derived(value);

  export function getContenteditable(): HTMLSpanElement | null {
    return contenteditableEl;
  }

  function selectContent(): void {
    setTimeout(() => {
      const el = contenteditableEl;
      if (!el) {
        return;
      }

      const range = document.createRange();
      range.selectNodeContents(el);
      const sel = window.getSelection();
      sel?.removeAllRanges();
      sel?.addRange(range);
    }, 10);
  }

  function handleBlur(e: FocusEvent): void {
    setTimeout(() => {
      if (contenteditableEl) {
        internalValue = contenteditableEl.innerText.trim() || value;
        value = internalValue;
        onValueChange?.(internalValue);
      }
      onBlur?.(e);
    }, 1);
  }

  function focusContenteditable(): void {
    contenteditableEl?.focus();
  }

  function blurContenteditable(): void {
    contenteditableEl?.blur();
  }

  function handlePencilClick(): void {
    focusContenteditable();
    if (selectOnEditClick) {
      selectContent();
    }
  }
</script>

<div
  class="group/contenteditable relative overflow-visible {className} {iconInline ? 'flex items-center' : ''}"
  {style}
>
  <span
    bind:this={contenteditableEl}
    dir="auto"
    contenteditable={editable}
    role="textbox"
    tabindex={editable ? 0 : undefined}
    style="min-width: 2px"
    class="peer outline-none focus:block {iconInline ? 'inline' : 'block'}"
    onkeydown={(e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        blurContenteditable();
      }
    }}
    onfocus={(e) => onFocus?.(e)}
    onblur={handleBlur}
  >
    {internalValue}
  </span>
  {#if withRequired}
    <span title="Required" class="text-red-500 peer-focus:hidden" onclick={focusContenteditable} role="presentation"
      >*</span
    >
  {/if}
  <SvgIcon
    name="pencil"
    class="flex-none cursor-pointer align-middle opacity-0 group-hover/contenteditable:opacity-100 group-hover/contenteditable-container:opacity-100 peer-focus:hidden {editable
      ? ''
      : 'invisible'} {withRequired ? '' : 'ml-1'} {iconInline ? 'inline align-bottom' : 'absolute'}"
    style={iconInline ? undefined : `right: ${-(1.1 * iconWidth)}px`}
    title="Edit"
    width={iconWidth}
    height={iconWidth}
    stroke-width={iconStrokeWidth}
    onclick={handlePencilClick}
  />
</div>

// web/src/components/field/Contenteditable.vue
<template>
  <div class="group/contenteditable relative overflow-visible" :class="{ 'flex items-center': !iconInline }">
    <span
      ref="contenteditable"
      dir="auto"
      :contenteditable="editable"
      style="min-width: 2px"
      :class="iconInline ? 'inline' : 'block'"
      class="peer outline-none focus:block"
      @keydown.enter.prevent="blurContenteditable"
      @focus="$emit('focus', $event)"
      @blur="onBlur"
    >
      {{ value }}
    </span>
    <span v-if="withRequired" title="Required" class="text-red-500 peer-focus:hidden" @click="focusContenteditable()"
      >*</span
    >
    <SvgIcon
      name="pencil"
      class="flex-none cursor-pointer align-middle opacity-0 group-hover/contenteditable-container:opacity-100 group-hover/contenteditable:opacity-100 peer-focus:hidden"
      :style="iconInline ? {} : { right: -(1.1 * iconWidth) + 'px' }"
      title="Edit"
      :class="{
        invisible: !editable,
        'ml-1': !withRequired,
        absolute: !iconInline,
        'inline align-bottom': iconInline
      }"
      :width="iconWidth"
      :height="iconWidth"
      :stroke-width="iconStrokeWidth"
      @click="[focusContenteditable(), selectOnEditClick && selectContent()]"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";

const props = defineProps({
  modelValue: {
    type: String,
    required: false,
    default: ""
  },
  iconInline: {
    type: Boolean,
    required: false,
    default: false
  },
  iconWidth: {
    type: Number,
    required: false,
    default: 30
  },
  withRequired: {
    type: Boolean,
    required: false,
    default: false
  },
  selectOnEditClick: {
    type: Boolean,
    required: false,
    default: false
  },
  editable: {
    type: Boolean,
    required: false,
    default: true
  },
  iconStrokeWidth: {
    type: Number,
    required: false,
    default: 2
  }
});

const emit = defineEmits(["update:model-value", "focus", "blur"]);

const value = ref(props.modelValue);
const contenteditableRef: any = ref();

watch(
  () => props.modelValue,
  (newValue) => {
    value.value = newValue;
  },
  { immediate: true }
);

function selectContent(): void {
  const el = contenteditableRef.value;
  const range = document.createRange();
  range.selectNodeContents(el);
  const sel = window.getSelection();
  sel?.removeAllRanges();
  sel?.addRange(range);
}

function onBlur(e: any): void {
  setTimeout(() => {
    if (contenteditableRef.value) {
      value.value = contenteditableRef.value.innerText.trim() || props.modelValue;
      emit("update:model-value", value.value);
    }
    emit("blur", e);
  }, 1);
}

function focusContenteditable(): void {
  contenteditableRef.value?.focus();
}

function blurContenteditable(): void {
  contenteditableRef.value?.blur();
}
</script>
